[workspace]
resolver = "2"
members = ["crates/sshoal-core", "app/sshoal"]

[workspace.package]
edition = "2024"
version = "0.0.1-beta.1"
license = "MIT"
repository = "https://github.com/japananh/sshoal"

[workspace.dependencies]
sshoal-core = { path = "crates/sshoal-core" }

tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "process", "sync", "net", "io-util"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
async-trait = "0.1"
thiserror = "2"
